src/content/2.1/Declarative Programming.tex
src/content/2.2/Limits and Colimits.tex
src/ctfp.texi
src/preamble.tex

This contains commits from #43 as well as some tweaks.

Chapters 2.1 and 2.2

---

src/content/1.7/Functors.tex

Fixes two small grammatical mistakes.

Fix grammar

---

src/content/1.5/Products and Coproducts.tex

I'm almost done the chapter - maybe hold off merging until I get to the end?

Make `Either` example into real Haskell

---

.travis.yml
shell.nix

@hmemcpy This is what needs to be done to use the `shell.nix` in the Travis build.  But we should try out whether the whole release thing still works :)

Use nix to build the pdf

---

src/content/1.5/Products and Coproducts.tex
src/content/3.3/Free-Forgetful Adjunctions.tex
src/content/3.6/Monads Categorically.tex

Minor fixes to make code snippets consistent with original source and scala translation.

Consistency with source

---

src/content/1.10/Natural Transformations.tex

add spaces to function signature in section 1.10.1

---

.travis.yml
default.nix
shell.nix

I fixed nix build to work with default.nix.

fixed nix build

---

src/Makefile

According to #208, and space by my editor (I hope you're fine with it).
- replace `echo` command with `printf`
- striped trailing whitespaces
tested - on my system, it generated equivalent pdfs.

replace echo with printf

---

src/content/1.1/category-the-essence-of-composition.tex

“if it were trivial...” -> “if it was trivial...”

Fixed a typo

---

pinned.nix
shell.nix

A fair bit of this PR is stylistic, so feel free to reject or request significant changes if you feel I've overstepped any bounds on the project!
---
I wanted to build this locally, but I ran into some problems. I got a little carried away and ended up refactoring `shell.nix` a bit as well as pinning everything to a specific commit of nixpkgs in the process 😅.
On the LaTeX side, it looks like the project needed `zref`, `catchfile`, and `import` from CTAN; dropping those into the `texlive` bundle seemed to resolve my issues there.
Since I was doing all of that anyway, I decided to go ahead and manage the two Python dependencies with Nix as well. This feels a bit nicer than managing them with virtualenv, and it would probably make it a bit easier to build this project with Nix if someone …

Nix tweaks

---

src/content/2.3/free-monoids.tex

I think choose was meant here.

Typo: s/chose/choose/

---

src/content/3.4/monads-programmers-definition.tex

Typo: choose rather than chose

---

.github/workflows/build.yaml

This PR
Example of this here: https://github.com/loophp/DockLatex/releases

Update automatic tag name.

---

src/content/1.1/category-the-essence-of-composition.tex

Reverts hmemcpy/milewski-ctfp-pdf#248

Revert "Fixed a typo"

---

errata-1.3.0.md
src/content/0.0/preface.tex
src/content/2.2/limits-and-colimits.tex

Mac Lane's book is _Categories for the Working Mathematician_, not _Category Theory for the Working Mathematician_.

Fix Mac Lane reference

---

.github/workflows/build.yaml
.gitignore
flake.lock
flake.nix
shell.nix
src/Makefile

Fix builds - use Nix for building

---

.github/workflows/build.yaml
flake.nix

This PR:
Props @aszlig ! I learned a lot by reading what you did !

Improvements in the Nix and build system.

---

src/content/1.7/functors.tex

Added missing figure (functorid.jpg) in src/content/1.7/functors.tex.

Add missing figure (#290)

---

src/content/3.5/code/scala/snippet30.scala

fix trivial typo in scala snippet

---

flake.lock
flake.nix

It has been added to Nix at: https://github.com/NixOS/nixpkgs/pull/214015

fix: remove custom `pygments-style-github`

---

.github/workflows/nix-flake-check.yaml
.github/workflows/release.yaml
flake.lock
flake.nix

Fix `fullname` variable

---

flake.lock

This PR fixes the prettier check in the CI workflow.

Fix prettier check

---

src/content/2.5/the-yoneda-lemma.tex
src/content/3.1/its-all-about-morphisms.tex

style: Use \mathit for Nat

---

src/content/1.4/kleisli-categories.tex
src/content/1.9/code/haskell/snippet11.hs

style: Wrap long line of code

---

src/content/3.5/monads-and-effects.tex

fix: Dead link in 21.1
