hmemcpy/milewski-ctfp-pdf

- src/content/1.2/Types and Functions.tex
- src/content/3.4/Monads - Programmer's Definition.tex
In some regions 'programing' is considered a correct spelling, but since the author uses 'programming' in all but two places I am assuming these two instances are typos.
> fix two typos of programing -> programming

- src/content/0.0/Preface.tex
Use the fix proposed in https://github.com/hmemcpy/milewski-ctfp-pdf/issues/47#issuecomment-333355364: Java did NOT let lambdas in C++.
Credits to @DevJac for figuring out the correct fix.
> Fix #47 better

- src/content/2.1/Declarative Programming.tex
- src/content/2.2/Limits and Colimits.tex
- src/content/2.3/Free Monoids.tex
- src/content/2.4/Representable Functors.tex
- src/content/2.5/The Yoneda Lemma.tex
- src/content/2.6/Yoneda Embedding.tex
Replaced `code{}` with `$$` and removed redundant
commandchars from verbatim blocks
> convert part 2 to math

- src/content/1.10/Natural Transformations.tex
- src/content/1.5/Products and Coproducts.tex
- src/content/1.6/Simple Algebraic Data Types.tex
- src/content/1.8/Functoriality.tex
- src/content/1.9/Function Types.tex
- src/content/2.1/Declarative Programming.tex
- src/content/2.4/Representable Functors.tex
- src/content/2.5/The Yoneda Lemma.tex
- src/content/3.10/Ends and Coends.tex
- src/content/3.11/Kan Extensions.tex
- src/content/3.12/Enriched Categories.tex
- src/content/3.13/Topoi.tex
- src/content/3.14/Lawvere Theories.tex
- src/content/3.15/Monads, Monoids, and Categories.tex
- src/content/3.4/Monads - Programmer's Definition.tex
- src/content/3.6/Monads Categorically.tex
- src/content/3.7/Comonads.tex
- src/content/3.8/F-Algebras.tex
- src/content/3.9/Algebras for Monads.tex
I made some minor spelling corrections.
Note: unfortunately my editor feels that every line, including the last one, should end with a newline character so the last line of each file I changed also shows as changed in the diffs.
I did also start correcting "cartesian" (spelled with a small "c") to "Cartesian" but then decided to leave this alone. Using a capital "C" however does seem to be the norm, e.g. if you look at [Cartesian product on Wikipedia](https://en.wikipedia.org/wiki/Cartesian_product) or on [Wolfram](http://mathworld.wolfram.com/CartesianProduct.html).
> Corrected occasional misspelling of Lawvere and other minor spelling mistakes, and capitalized Cartesian

- src/content/1.10/Natural Transformations.tex
Fixes issue #91.
I believe there is a typo in section 10.4 2-Categories. The sentence "In fact they are members of two different functor categories:" is followed by categories `D^E` and `E^D`. I believe the intent was `D^C` and `E^D` as we are talking about the morphisms on morphisms α and β, with :
```
α :: F → F′
β :: G → G′
F :: C → D
G :: D → E```
> Fix a typo in the category of a morphism on morphisms.

- src/content/1.8/Functoriality.tex
The type :: and definition (=) should be expressed on separate lines, as they are in the blog.
> Update return defn in Functoriality.tex

- README.md
Updated README with details of the Libertinus Math font dependency, and the site from where the font can be downloaded for free.
> Adding Libertinus Math font dependency for building on macOS to README

- src/content/1.10/Natural Transformations.tex
- src/content/1.6/Simple Algebraic Data Types.tex
- src/content/1.9/Function Types.tex
And the addition of a `data` for a Haskell valid structure (the examples right before are also using it, I think it makes sense to be consistent)
> Minor typos

- src/content/3.6/Monads Categorically.tex
Switched 'lambda' and 'rho'. Lines 282 and 283 were correct.
> Update Monads Categorically.tex

- shell.nix
This is needed to ensure the use of TeX Live 2017, see [this tweet](https://twitter.com/hmemcpy/status/1033352444280033280) for details.
> shell.nix: pin nixpkgs to recent 18.03

- shell.nix
- src/preamble.tex
Fixes #144 (and fixes #124)
Reverts a pinning change to nix script to pull the latest (2018) TexLive.
> Texlive 2018 support

- src/content/2.4/Representable Functors.tex
In the chapter on [Representable Functors](https://bartoszmilewski.com/2015/07/29/representable-functors/), what should read as
> -<sup>a</sup> = F
is currently appearing as
> -a = F
I was pretty confused until I looked up the original text. :joy:
------
By the way, thanks for making this—it's been a joy to read on my Kindle!
> Fix typo in Chapter 14.

- src/content/3.3/Free-Forgetful Adjunctions.tex
In the chapter on [Free/Forgetful Adjunctions](https://bartoszmilewski.com/2016/06/15/freeforgetful-adjunctions/), an instance of the category name **Mon** is currently appearing as **arg**. (Looks like the problem was introduced [here](https://github.com/hmemcpy/milewski-ctfp-pdf/commit/51a71ee475724e8201c5d9b62b4ba92bd0471733#diff-a8491c5119dff7c11d41b4edab18ab5cR53).)
> Fix typo in Chapter 19.

- src/content/3.7/Comonads.tex
- src/content/3.9/Algebras for Monads.tex
The chapters on [Comonads](https://bartoszmilewski.com/2017/01/02/comonads/) and [Algebras for Monads](https://bartoszmilewski.com/2017/03/14/algebras-for-monads/) each feature a Haskell function named `set`, but this is being typeset as if it were the category **Set** in two places (as of #56).
> Fix typos in Chapters 23 and 25.

- src/content/3.10/Ends and Coends.tex
- src/content/3.9/Algebras for Monads.tex
The chapters on [Algebras for Monads](https://bartoszmilewski.com/2017/03/14/algebras-for-monads/) and [Ends and Coends](https://bartoszmilewski.com/2017/03/29/ends-and-coends/) have a few typesetting issues (which were introduced in #66):
- An instance where "object _a_" is written as "object _A_"
- Two instances where the Kleisli category **C**<sub>_T_</sub> is written as **C**<sup>_T_</sup>
- Two instances where → is written as `->`
-----
By the way, so far I've only been making corrections when the TeX differs from the original text, but I notice there are a couple of spelling errors as well as another typesetting error (µ<sub>_T_ _b_</sub> instead of µ<sub>_Tb_</sub>) which are also present in the original text. Should I fix these as well, or somehow make note of them separately?
> Fix typesetting issues in Chapters 25 and 26.

- src/content/1.6/code/scala/snippet22.scala
This fixes the issue https://github.com/hmemcpy/milewski-ctfp-pdf/issues/179 by making the type parameters in the OneOfThree Scala example covariant.
(Is this all that needs to be done to fix this?)
> Fix OneOfThree Scala example

- src/Makefile
Hi @hmemcpy !
I'm preparing the files for Kotlin edition and I saw this comment in `Makefile`:
```
#remove this awful duplication ASAP
```
This **super tiny** _pull request_ is making a proposal for removing that duplication.
The variable definition is not necessary for the `copy` target so this line could be removed:
```
copy: suffix = ''
```
However, I prefer to make things explicit. 
You'll see something like:
```
mv ctfp-reader''.pdf ../out/v1.3.0-2-gf7db7ca/category-theory-for-programmers''.pdf
mv ctfp-print''.pdf ../out/v1.3.0-2-gf7db7ca/category-theory-for-programmers''-print.pdf
```
or:
```
mv ctfp-reader'-scala'.pdf ../out/v1.3.0-2-gf7db7ca/category-theory-for-programmers'-scala'.pdf
mv ctfp-print'-scala'.pdf ../out/v1.3.0-2-gf7db7ca/category-theory-for-programmers'-scala'-print.p …
```
> Refactor: remove duplication in Makefile

- src/content/1.6/code/scala/snippet34.scala
Explicitly Tupling return in `prodToSum` method in Chapter 6
Mostly because it will produce these warnings if "-Xlint:adapted-args" is turned on, and it makes more clear that `sumToProd` is the inverse function as it does tuple the pair in the pattern match
```
[REDACTED]/src/main/scala/Main.scala:5:30: adapted the argument list to the expected 2-tuple: add additional parens instead
[warn]         signature: Left.apply[A, B](value: A): scala.util.Left[A,B]
[warn]   given arguments: x, y
[warn]  after adaptation: Left((x, y): (A, B))
[warn]         case Left(y)  => Left(x, y)
[warn]                              ^
[warn] [REDACTED]/src/main/scala/Main.scala:6:31: adapted the argument list to the expected 2-tuple: add additional parens instead
[warn]         signature: Right.apply[A, …
```
> Tupeling return type in prodToSum method in section 6.4

- src/cover/ribbon-ocaml.tex
- src/cover/ribbon-reason.tex
It was probably not obvious, since I reused the OCaml color in Reason, but: Now that I changed it to the actual ReasonML color, I found out that I accidentally overwrote the `BurntOrange` color for OCaml.
> Fix OCaml and ReasonML ribbon colors

- src/content/1.8/code/haskell/snippet10.hs
In the instance declaration of `BiComp`.
> Remove unnecessary brackets

- src/colophon.tex
Well, the colophon uses the word "LaTeX" twice; the latter use was not rendered with the nice macro. This fixes it.
> Make the second "LaTeX" in the Colophon a macro

- src/content/1.6/code/ocaml/snippet20.ml
See: page 89 of the OCaml version of the book.
Before:
After:
> Fix formatting in the OCaml snippet

- src/content/1.8/code/ocaml/snippet13.ml
The `t` I added actually stands for `BiCompBiFunctor.t` but technically `bimap` is defined inside the module so I omitted the module name.
> Fix error in type for bimap

- src/content/1.8/code/ocaml/snippet01.ml
- src/content/1.8/code/ocaml/snippet09.ml
- src/content/1.8/code/ocaml/snippet14.ml
- src/content/3.2/code/ocaml/snippet06.ml
- src/content/3.8/code/ocaml/snippet31.ml
A few more fixes for OCaml code snippets (related: #277). The problem is that we don't have automatic wrapping for OCaml comments when render them in LaTeX. So we have to set new lines manually.
I found this while reading chapter 8, then I created a [small script](https://gist.github.com/jubnzv/c2c8b2edd4d739a28f32107905235795), which finds similar cases among all code snippets.
<details>
<summary>Screenshots (before / after)</summary>
</details>
> Fix formatting in OCaml snippets

- src/content/1.7/functors.tex
Fix missing apostrophe: "Now, lets show..." -> "Now, let's show...".
> Fix missing apostrophe

- README.md
Before this commit the instructions in the README.md weren't accurate enough to allow one to build the Scala version of the PDF following them (`make` and `make scala` failed miserably).
In this commit I did my best to transfer the updated instructions that were given by @drupol at issue #288 and I can confirm that they work like a charm on my GNU/Linux laptop.
Thanks !
> Updated README.md as per issue #288

- src/content/1.2/types-and-functions.tex
Added a missing comma.
My neovim settings also automatically removed trailing whitespaces and added a newline at the end in the process. I figured I should keep it as is and ask whether that should be reverted or not.
> Add missing comma

- src/content/3.2/adjunctions.tex
- 'iff' normally means 'if and only if', which is stronger than just 'if'. https://en.wikipedia.org/wiki/If_and_only_if
- See the discussion on #294
> Revert wrong "typo fix" for "iff"

- src/category.tex
- src/content/1.5/products-and-coproducts.tex
- src/content/1.8/functoriality.tex
- src/content/1.9/function-types.tex
- src/content/2.2/limits-and-colimits.tex
- src/content/2.4/representable-functors.tex
- src/content/2.5/the-yoneda-lemma.tex
- src/content/2.6/yoneda-embedding.tex
- src/content/3.10/ends-and-coends.tex
- src/content/3.12/enriched-categories.tex
- src/content/3.13/topoi.tex
- src/content/3.14/lawvere-theories.tex
- src/content/3.15/monads-monoids-and-categories.tex
- src/content/3.2/adjunctions.tex
- src/content/3.6/monads-categorically.tex
- src/content/3.8/f-algebras.tex
- src/content/3.9/algebras-for-monads.tex
By default, in math environment, each letter is a separate identifier or variable, so a consecutive sequence of letters typically means multiplication of several variables. To represent a multi-letter identifier, it’s better to wrap it in `\mathit{}`. Without `\mathit{}`, the result identifier would have awkward spacings between each letter.
> Use `\mathit` for multi-letter identifiers

- src/content/1.7/functors.tex
- src/content/2.2/limits-and-colimits.tex
This PR contains two fixes:
1. Use small circles for morphism compositions in math environment.
2. Replace a `\code{c}` with `$c$`, because only `$c$` is referred in the context, `\code{c}` does not make sense.
> Small fixes

- README.md
Greetings!
This commit updates the the link from the former, unofficial nixos wiki page to the new https://wiki.nixos.org
ref: NixOS/foundation#113
> readme: update NixOS wiki link

- src/content/3.2/adjunctions.tex
- src/content/3.9/algebras-for-monads.tex
Replace `\epsilon` with `\varepsilon` for consistency.
> Use consistent epsilon symbol

- src/content/1.10/natural-transformations.tex
- src/content/3.1/its-all-about-morphisms.tex
I found some functors are rendered with normal font instead of math font.
> fix: Use math font for functors

- src/content/3.7/comonads.tex
cf. https://hackage.haskell.org/package/lens
> fix: Lens library name should be lower-case

- src/content/1.6/simple-algebraic-data-types.tex
- src/content/1.9/function-types.tex
- src/content/2.2/limits-and-colimits.tex
- src/content/3.10/ends-and-coends.tex
There are some suggestions from a reviewer of the Japanese version for the chapter 1.6:
- `case of` is a clause, not a statement
- Add missing `data` keyword
- `stmt :: Pair String Bool` is a type signature, not a type declaration
- Remove trailing spaces in Haskell code
> Small fixes for 1.6
